- name: upgrade all packages
  dnf:
    name: '*'
    state: latest

- name: install dnf packages
  dnf:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
  with_items: '{{ dnf_packages }}'
