---
all:
  hosts:
    local:
      ansible_connection: local
      ansible_host: localhost
  children:
    aws:
      hosts:
        wp_server:
      vars:
        ansible_host: '{{ wp_public_ip }}'
        ansible_ssh_private_key_file: /root/.ssh/tf-key-pair