---
- name: create AWS infrastructure
  hosts: local
  connection: local
  gather_facts: true
  roles:
    - terraform
  tags: aws

- name: build wordpress
  hosts: aws
  user: ec2-user
  become: true
  roles:
    - dnf
    - wordpress
  tags: wp